# based on the latest ubuntu
FROM ubuntu:latest

# Update APT using apt-get update
RUN apt-get update

# Upgrade currently installed software through APT
RUN apt-get upgrade -y

# Once running Docker image in container, "hello, world!" displays
CMD ["echo", "Hello, World!"]
